Rethrow exceptions that make it to the main module
bfa36136dac787793bc5106da57cccbb8db1ce14 broke the exception system by
completely swallowing any exceptions. This patch "repairs" it by
rethrowing exceptions that bubble up to the main module. However, this
changes the stack trace output from:

----
node.js:22
  throw new Error("p() has moved. Use require('sys') to bring it back.");
        ^
Error: p() has moved. Use require('sys') to bring it back.
----

to:

----
node.js:962
  throw e;
  ^
Error: p() has moved. Use require('sys') to bring it back.
----